plugins {
    id("quranengine.compose.library")
    alias(libs.plugins.ksp)
}

android { namespace = "com.quranengine.features.quranview" }

dependencies {
    implementation(project(":ui:theme"))
    implementation(project(":ui:components"))
    implementation(project(":ui:quran"))
    implementation(project(":ui:pager"))
    implementation(project(":ui:audio-banner"))
    implementation(project(":features:quran-image"))
    implementation(project(":features:quran-pages"))
    implementation(project(":features:quran-content"))
    implementation(project(":features:quran-translation"))
    implementation(project(":features:audio-banner"))
    implementation(project(":model:quran-kit"))
    implementation(project(":model:quran-text"))
    implementation(project(":model:quran-annotations"))
    implementation(project(":model:quran-geometry"))
    implementation(project(":core:localization"))
    implementation(project(":domain:quran-text-kit"))
    implementation(project(":domain:annotation-service"))
    implementation(project(":domain:image-service"))
    implementation(project(":domain:reading-service"))
    implementation(project(":domain:translation-service"))
    implementation(project(":core:preferences"))
    implementation(project(":data:sqlite-persistence"))
    implementation(project(":data:word-frame-persistence"))
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.material3)
    implementation(libs.compose.material.icons.extended)
    implementation(libs.compose.foundation)
    implementation(libs.compose.runtime)
    implementation(libs.lifecycle.runtime.compose)
    implementation(libs.lifecycle.viewmodel.compose)
    implementation(libs.hilt.navigation.compose)
    implementation(libs.coroutines.core)
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)
    implementation(libs.timber)
}
